services:
  - type: web
    name: floormap-web
    env: docker
    plan: starter
    region: singapore
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: 'true'
    healthCheckPath: '/up'
