---
:verbose: false
:timeout: 25
:max_retries: 5

:concurrency: 5
:max_dead_letter_jobs: 10000

:queues:
  - critical
  - default
  - low

development:
  :concurrency: 2

production:
  :concurrency: 10
  :timeout: 30
